os:
  - linux

language: node_js

node_js:
  - '6.5'

branches:
  only:
    - master
    - origin/ready/**

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "sleep 3" # give xvfb some time to start
  - npm run package:linux

script:
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

test_script:
  - npm test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change