os:
- linux

language:
- node_js

node_js:
- '6.5'

branches:
  only:
  - master
  - /^ready\/.*$/
  - /^(?i:ready)-.*$/


before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- npm run package:linux
- export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH;
  else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
- echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"

test_script:
- npm test

after_success:
- if [ "$BRANCH" != "master" ]; then
  git clone "https://github.com/RCTechnologies/Seed.git" repo_temp;
  cd repo_temp;

  echo ls;
  ls;

  echo Checkout;
  git checkout "master";

  echo Mergin;
  git merge --ff-only "$TRAVIS_BRANCH";

  echo Pushing;
  push_uri="https://$GH_TOKEN@github.com/RCTechnologies/Seed";

  else echo Was PULLREQUEST or directly on master; fi

cache:
  directories:
  - node_modules
notifications:
  email:
    on_success: never
    on_failure: change
env:
  global:
    secure: TFC7VXV1Lit7tcYGcgcMXOaIIdZ8ph1nIKmntl0Fd+n6oD2U5qvrmkb/kT3V/+YcuRO3fC6INEyiZ3X5Czass9WSLo/YzgVkWyrN6e7FR0xYWazApwUZGhJc4irUR/UN3gOuQl3uPhE2Q3kckeqg11GfZU/LemjoWzjHwdn9fqAEskyAaRLIAN/YxNVOroqvwo6zdV6zPKsQQl5YPZDcGGGpL0eV0/6YnqRrsGaXP6NiBRfLyGqVp45cLDdZc87hUG4jqr8Bfk18GZQzh6T+JsD8lCUbRCYAfbYiNpzcD5flHtv7/xMKcKdPttY4Zvnmql3oqXtmkkwD1Y7luYLq8/FpyCFyRi+PfR7D8fNdKc4HklGwub2AVgEXwZiRiAwcFpil8+Gbn15oJ86kFykdHG083iXJB34rzZFTwnwdRbOSE1EnLv5ou1r/IYWrQ+yIjCxhk4U9KyJbXsRdSVxrNZaSl5s68suytxuoTiPdGpqjiTGOMhu//yc8aHKoWOHFmZE+DPpvmTgDsfDXX9V5+2zIwekLWy73YDZkZd1cpAaE5ehbLbMBw1ekmDCBqCLMIn3LfAaNmacLRkq39ChFhtg16vMQ6m9ATpCVvdLt1rSRye8I48+/PHeQ8p4q1fDr9msYSBUGsKkI8ETcaxuex2OIYKWtLK5+/JDCkX5o2NU=
