os:
  - linux

language: node_js

node_js:
  - '6.5'

branches:
  only:
    - master

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
  - npm run package:linux

test_script:
  ##- node --version
  ##- .\node_modules\.bin\npm --version
  - npm run test

cache:
  directories:
    - node_modules

notifications:
  email:
    on_success: never
    on_failure: change